

credentials:
  usernames:
    admin:
      email: mend3s.c@outlook.com
      name: Administrador do Sistema
      password: 'admin'
      role: 'admin'
    
    joao:
      email: joaooguilherme.dev@gmail.com
      name: João Silva
      password: '2'
      role: 'user'

    Edu:
      email: edu@example.com
      name: Eduardo Carlos
      password: 'hashed_password_for_edu'
      role: 'admin'
      

cookie:
  expiry_days: 30
  key: 'strong_key'
  name: 'cookie_da_academia_app'

preauthorized:
   emails:
     - mend3s.c@gmail.com